### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by kkoci** [totaler/mongodb_backend#18]
Hi, I'm new into mongodb and I was wondering if it was possible to use it with OpenERP/Odoo instead of PostgreSQL.

BTW, I just want to know, if this was tested on 6.0, 6.1, 7.0 or even 8.0 Odoo versions?

Or just v5.0?

Thanks in advance!

**Comment by totaler** [comment]
Hello. MongoDB as a non relational no-sql database it is not suitable for substituting PostgreSQL. For example openerp relies a lot in transactions for maintaining referential integrity and a healthy db, and mongodb just does not work this way. This module is intended to work in addition to PostgreSQL, for example, storing huge tables or attachments.

It is not tested with versions older than 5.0, but it should work with very few modifications until v7.0.

**Comment by kkoci** [comment]
Oh, right, well, I will try it then!

Ya, we should wait until NoSQL databases get that issue sorted, I think there is one which can support something like transactions, but I don't remember it's name right now.

Anyways, thank you very much! I will try it.
